name: nike-landing-ci-cd
on: [push]
jobs: 
  deploy-nike-landing:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Deploy to Railway Hosting
      with: {
          "args": "railway up --project nike-landing"
        }